export {default as Home} from './Home'
export {default as CreatePage} from './CreatePage'
export {default as SignUp} from './SignUp'
export {default as SignIn} from './SignIn'
export {default as SinglePage} from './SinglePage'
export {default as NotFound} from './NotFound'